SYSTEM_NAME = "LandLedger ERP"

VOUCHER_TYPE_RECEIPT = "سند قبض"
VOUCHER_TYPE_PAYMENT = "سند صرف"

ACCOUNT_LEVEL_MAIN = "رئيسي"
ACCOUNT_LEVEL_SUB = "فرعي"
ACCOUNT_LEVEL_ASSISTANT = "مساعد"
ACCOUNT_LEVEL_ANALYTICAL = "تحليلي"

ACCOUNT_LEVELS = [
    ACCOUNT_LEVEL_MAIN,
    ACCOUNT_LEVEL_SUB,
    ACCOUNT_LEVEL_ASSISTANT,
    ACCOUNT_LEVEL_ANALYTICAL,
]

# Sub-ledger control accounts
CUSTOMER_CONTROL_ACCOUNT_CODE = "1104"
VENDOR_CONTROL_ACCOUNT_CODE = "2101"

# HTML -> PDF preview subsystem
WKHTMLTOPDF_PATH = ""
REPORT_PREVIEW_TEMP_DIR = ""
